name: 'Setup Kubeconform'
description: 'Sets up the Kubeconform CLI in your GitHub Actions workflow.'
author: 'Benjamin Muschko'
inputs:
  kubeconform-version:
    description: 'The version of the Kubeconform CLI to install.'
    default: '0.6.3'
    required: false
outputs:
  installation-path:
    description: 'The installation path of Kubeconform, empty if it couldn't be installed.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'purple'