name: 'Build and Test'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-dist:
    name: Check dist/ directory
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@1e97bade5ca12552a4d14d19ef769e9667ad73c4
    with:
      node-version: 24.x
      node-caching: npm

  test:
    name: Test
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@6e6fbc184bf30831203760e82e414987073f4a47
    with:
      node-version: 24.x
      node-caching: npm
