name: Integration Test
on: [push, pull_request]

jobs:
  integration-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Node.js 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.x
          cache: npm
      - name: Build distribution
        shell: bash
        run: |
          npm install
          npm run build
      - name: Set up kubeconform
        id: setup-kubeconform
        uses: ./
      - name: Print Kubeconform installation path
        env:
          KUBECONFORM_INSTALLATION_PATH: ${{ steps.setup-kubeconform.outputs.installation-path }}
        run: |
          echo "Kubeconform installed..."
          echo "Installation path: ${KUBECONFORM_INSTALLATION_PATH}"
        shell: bash
      - name: Render kubeconform version
        run: kubeconform -v
        shell: bash
      - name: Create Pod YAML file
        run: |
            cat <<EOT >> pod.yaml
                apiVersion: v1
              kind: Pod
              metadata:
                name: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                  - containerPort: 80
            EOT
        shell: bash
      - name: Validate a Pod YAML file with kubeconform
        run: kubeconform -summary -verbose pod.yaml
        shell: bash
